Sparkling.Xelect.js.Mvc.Ext/Sparkling.Xelect.js.Mvc.Demo/Models/AcModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sparkling.Xelect.js.Mvc.Demo.Models
{
    public class Entity
    {
        public int Id { get; set; }
    }

    public class Contact : Entity
    {
        public string Name { get; set; }
    }

    public class Clv : Entity
    {
        public string Value { get; set; }
        public int TypeId { get; set; }
    }
}

Sparkling.Xelect.js.Mvc.Ext/Sparkling.Xelect.js.Mvc.Demo/Models/DemoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Sparkling.Xelect.js.Mvc.Ext;

namespace Sparkling.Xelect.js.Mvc.Demo.Models
{
    public class DemoModel
    {
        public int? ContractorId { get; set; }
        public string ContractorName { get; set; }

        public int? BuyInGroupId { get; set; }
        public string BuyInGroupName { get; set; }

        public XelectCollection Names { get; set; }
    }
}

Sparkling.Xelect.js.Mvc.Ext/Sparkling.Xelect.js.Mvc.Demo/Controllers/AcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sparkling.Xelect.js.Mvc.Demo.Models;

namespace Sparkling.Xelect.js.Mvc.Demo.Controllers
{
    public class AcController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="typeId"></param>
        /// <param name="q"></param>
        /// <param name="excludeIds"></param>
        /// <returns></returns>
        public ActionResult Clv(int? typeId, string q, int[] excludeIds)
        {
            var values = new List<Clv>()
            {
                new Clv() { Id = 1, Value = "Test1", TypeId = 1 },
                new Clv() { Id = 2, Value = "Test20", TypeId = 1 },
                new Clv() { Id = 3, Value = "Test300", TypeId = 3 },
                new Clv() { Id = 4, Value = "Test4000", TypeId = 4 },
                new Clv() { Id = 5, Value = "Test50000", TypeId = 7 },
                new Clv() { Id = 6, Value = "Test600000", TypeId = 7 },
                new Clv() { Id = 7, Value = "Test610000", TypeId = 7 },
                new Clv() { Id = 8, Value = "Test620000", TypeId = 7 },
                new Clv() { Id = 9, Value = "Test630000", TypeId = 7 },
                new Clv() { Id = 10, Value = "Test640000", TypeId = 7 },
            };

            var seed = values
                .Where(x => x.Value.ToLower().Contains(q.ToLower())
                    && (!typeId.HasValue || x.TypeId == typeId));

            //prevent from reordering as the correct order is already set
            return Res(q, seed, x => x.Value, excludeIds, orderByName: false);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="q"></param>
        /// <param name="excludeIds"></param>
        /// <returns></returns>
        public ActionResult Contractor(string q, int[] excludeIds)
        {
            var values = new List<Contact>()
            {
                new Contact() { Id = 1, Name = "Name1" },
                new Contact() { Id = 2, Name = "Name20" },
                new Contact() { Id = 3, Name = "Name300" },
                new Contact() { Id = 4, Name = "Name4000" },
                new Contact() { Id = 5, Name = "Name50000" },
                new Contact() { Id = 6, Name = "Name600000" }
            };

            var seed = values
                .Where(x => x.Name.ToLower().Contains(q.ToLower()));

            return Res(q, seed, x => x.Name, excludeIds);
        }

        private ActionResult Res<T>(string q, IEnumerable<T> seed, Func<T, string> nameSelector, int[] excludeIds = null, int? limit = null, bool orderByName = true) where T : Entity
        {
            if (excludeIds == null)
            {
                excludeIds = new int[0];
            }

            var query = seed
                .Where(x => !excludeIds.Contains(x.Id))
                .Select(
                    x =>
                        new
                        {
                            i = nameSelector(x).IndexOf(q, StringComparison.OrdinalIgnoreCase),
                            value = new { id = x.Id, name = nameSelector(x) }
                        });

            if (orderByName)
            {
                query = query.OrderBy(x => x.i);
            }

            var res = query
                .Take(limit ?? 25)
                .Select(x => x.value)
                .ToArray();

            return Json(res, JsonRequestBehavior.AllowGet);
        }
    }
}

Sparkling.Xelect.js.Mvc.Ext/Sparkling.Xelect.js.Mvc.Demo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sparkling.Xelect.js.Mvc.Demo.Models;

namespace Sparkling.Xelect.js.Mvc.Demo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var model = new DemoModel()
            {
                
            };

            return View(model);
        }
    }
}

Sparkling.Xelect.js.Mvc.Ext/Sparkling.Xelect.js.Mvc.Demo/Views/Home/Index.cshtml
@using Sparkling.Xelect.js.Mvc.Ext
@model Sparkling.Xelect.js.Mvc.Demo.Models.DemoModel

<form method="post" action="temp" class="tempClass">
    <div class="form-item">
        <label>Hankija</label>
        <div>
            @Html.AutocompleteFor(x => x.ContractorName, Url.Action("Contractor", "Ac"), new { data_xelect_max_height = 3 })
            <span class="ac-hint-text">Hankija nimi</span>
            <span class="ac-no-results-text">Ühtegi hankijat ei leitud</span>
            <span class="ac-searching-text">Otsin...</span>
            @Html.ValidationMessageFor(x => x.ContractorId)
        </div>
    </div>

    <div class="form-item">
        <label>Ostuklass</label>
        <div>
            @Html.AutocompleteFor(x => x.BuyInGroupName, Url.Action("Clv", "Ac", new { typeId = 7, multiselect = true }), new { @class = "xelect-multiselect", data_field_id = 100, data_field_name = "pla" })
            <span class="ac-hint-text">Ostuklassi nimi</span>
            <span class="ac-no-results-text">Ühtegi ostuklassi ei leitud</span>
            <span class="ac-searching-text">Otsin...</span>
        </div>
    </div>

    <div class="form-item">
        <label>Ostuklass 2</label>
        <div>
            @Html.AutocompleteFor(x => x.Names, Url.Action("Clv", "Ac", new { typeId = 7 }))
            <span class="ac-hint-text">Ostuklassi nimi</span>
            <span class="ac-no-results-text">Ühtegi ostuklassi ei leitud</span>
            <span class="ac-searching-text">Otsin...</span>
        </div>
    </div>

    <div class="form-item">
        <label>Ostuklass 2</label>
        <div>
            @Html.Autocomplete("pla", Url.Action("Clv", "Ac", new { typeId = 7 }), null, "1", "Preselected")
            <span class="ac-hint-text">Ostuklassi nimi</span>
            <span class="ac-no-results-text">Ühtegi ostuklassi ei leitud</span>
            <span class="ac-searching-text">Otsin...</span>
        </div>
    </div>
    
    <div class="form-item">
        <label>Combobox</label>
        <div>
            @{
                var options = new []
                {
                    new SelectListItem
                    {
                        Text = "Option1",
                        Value = "1"
                    },
                    new SelectListItem
                    {
                        Text = "Option2",
                        Value = "2"
                    },
                    new SelectListItem
                    {
                        Text = "Option3",
                        Value = "3",
                        Selected = true
                    }
                };
            }
            @Html.Selector("combobox-test", options, new XelectParameters
            {
                RootAttributes = new
                {
                    type = "combobox",
                    name = "root",
                    data_pla = 100
                },
                ValueInputAttributes = new
                {
                    name = "valueinput",
                    data_value = 5
                },
                TextInputAttributes = new
                {
                    name = "textinput",
                    data_index = 1 
                }
            })
            <span class="ac-hint-text">Ostuklassi nimi</span>
            <span class="ac-no-results-text">Ühtegi ostuklassi ei leitud</span>
            <span class="ac-searching-text">Otsin...</span>
        </div>
    </div>
    
    <div class="form-item">
        <label>Template override shared</label>
        <div>
            @Html.Autocomplete("template-test", Url.Action("Clv", "Ac", new { typeId = 7 }), null, "1", "Preselected", "_Xelect")
            <span class="ac-hint-text">Ostuklassi nimi</span>
            <span class="ac-no-results-text">Ühtegi ostuklassi ei leitud</span>
            <span class="ac-searching-text">Otsin...</span>
        </div>
    </div>
</form>

@section scripts
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/node_modules/@brightspark/sparkling-observable-js/sparkling-observable.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/node_modules/@brightspark/sparkling-observable-js-property-changed-ext/sparkling-observable-property-changed-ext.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/node_modules/@brightspark/sparkling-ajax-js/sparkling-ajax.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/node_modules/@brightspark/sparkling-xelect-js/sparkling-xelect.js")"></script>
    <script type="text/javascript">
        (function () {
            Xelect = sparkling.Xelect;

            var x1 = new Xelect("xelect-for-ContractorName");

            var x2 = new Xelect("xelect-for-BuyInGroupName", {
                maxHeight: 3,
                multiselect: true
            });

            var x3 = new Xelect("xelect-for-Names", {
                forceValue: false,
                maxHeight: 8
            });

            var x4 = new Xelect("xelect-for-pla", {
                forceValue: false
            });
            var x5 = new Xelect("xelect-for-combobox-test");
        })();
    </script>
}

Sparkling.Xelect.js.Mvc.Ext/Sparkling.Xelect.js.Mvc.Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/site2.css" rel="stylesheet" type="text/css" />
    @*<link href="@Url.Content("~/Scripts/node_modules/@brightspark/sparkling-xelect-js/sparkling-xelect.min.css")" rel="stylesheet" type="text/css" />*@
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

Sparkling.Xelect.js.Mvc.Ext/Sparkling.Xelect.js.Mvc.Demo/Views/Shared/_Xelect.cshtml
@model Sparkling.Xelect.js.Mvc.Ext.XelectViewModel
<div>Custom Template for @Model.Id</div>